### ISSUE TITLE
AggregateException when migrating files

### ISSUE THREAD

**Issue by reikjarloekl** [tamhinsf/ChannelSurf#10]
File C:\Users\Joern\AppData\Local\Temp\tmp10D3.tmp\dummy_31_mechanik\2018-07-02.json

Unhandled Exception: System.AggregateException: One or more errors occurred. (Code: UnknownError

Inner error
) ---> Microsoft.Graph.ServiceException: Code: UnknownError

Inner error

   at Microsoft.Graph.HttpProvider.<SendAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendAsync>d__32`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ChannelSurfCli.Utils.FileAttachments.<UploadFileToTeamsChannel>d__3.MoveNext() in C:\work\meisterwerk\channelsurf\ChannelSurfCli\Utils\FileAttachments.cs:line 122
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ChannelSurfCli.Utils.Messages.CreateSlackMessageJsonArchiveFile(String basePath, ChannelsMapping channelsMapping, List`1 messageList, String aadAccessToken, String selectedTeamId) in C:\work\meisterwerk\channelsurf\ChannelSurfCli\Utils\Messages.cs:line 234
   at ChannelSurfCli.Utils.Messages.GetAndUploadMessages(ChannelsMapping channelsMapping, String basePath, List`1 slackUserList, String aadAccessToken, String selectedTeamId, Boolean copyFileAttachments) in C:\work\meisterwerk\channelsurf\ChannelSurfCli\Utils\Messages.cs:line 201
   at ChannelSurfCli.Utils.Messages.ScanMessagesByChannel(List`1 channelsMapping, String basePath, List`1 slackUserList, String aadAccessToken, String selectedTeamId, Boolean copyFileAttachments) in C:\work\meisterwerk\channelsurf\ChannelSurfCli\Utils\Messages.cs:line 19
   at ChannelSurfCli.Program.Main(String[] args) in C:\work\meisterwerk\channelsurf\ChannelSurfCli\Program.cs:line 168

Content of the JSON in question is:

[
    {
        "type": "message",
        "user": "A4U3A01V",
        "text": "Greg, Martin, did you receive the package in he mail today? Is it the „Full Assembly“?",
        "client_msg_id": "A425C095-4FE7-4D5E-8D62-A12D0BF39E35",
        "ts": "1530557117.000091"
    }
]

**Comment by tamhinsf** [comment]
Hi - can you manually edit the JSON file in question and remove  „Full Assembly“ - and then run the import again?  I'm guessing quotes surrounding Full Assembly need to be encoded on my end.
