### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Montana420** [tamhinsf/ChannelSurf#16]
Hi,

Really hoping someone might be able to help me out with this one.
I'm very new to this kind of thing. But i was at the final stage and have received this.

C:\Users\Cassidy's PC\Desktop\ChannelSurf-master\ChannelSurfCli>dotnet run dotnet run C:\Users\Cassidy's PC\Desktop\Virtual Dream Slack export Feb 10 2018 - Feb 26 2019.zip

****************************************************************************************************
Welcome to Channel Surf!
This tool makes it easy to bulk create channels in an existing Microsoft Team.
All we need a Slack Team export ZIP file whose channels you wish to re-create.
Or, you can define new channels in a file called channels.json.
****************************************************************************************************

**************************************************
Tenant is virtualdreaming.onmicrosoft.com
Application ID is 4c7fcc93-2bff-4171-8673-33c7fa041bb4
Redirect URI is https://channelsurf-cli
**************************************************

****************************************************************************************************
Your tenant admin consent URL is https://login.microsoftonline.com/common/oauth2/authorize?response_type=id_token&client_id=4c7fcc93-2bff-4171-8673-33c7fa041bb4&redirect_uri=https://channelsurf-cli&prompt=admin_consent&nonce=f4a8cab6-a8a9-4688-8238-6cf87bc3cbc8
****************************************************************************************************

****************************************************************************************************
Let's get started! Sign in to Microsoft with your Teams credentials:
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ************ to authenticate.
You've successfully signed in.  Welcome cassidy@virtualdream.com.au
Groups {"@odata.context":"https://graph.microsoft.com/beta/$metadata#groups","value":[{"id":"f59eb0c4-0744-4ea8-aded-f2ad197a39fa","displayName":"Virtual Dream","description":"Virtual Reality and 360 Production Services","isArchived":false}]}
You're currently a member of these Teams
WARNING: If you don't have permission to create new channels for a given Team, your attempt to create or migrate channels will fail
[0] Virtual Dream Virtual Reality and 360 Production Services
Enter the destination Team number or type "new" to create a new Team: 0
Team ID is f59eb0c4-0744-4ea8-aded-f2ad197a39fa
Creating temp directory for Slack archive decompression
Temp path is C:\Users\Cassidy's PC\AppData\Local\Temp\tmp6C32.tmp

Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\Cassidy's PC\Desktop\ChannelSurf-master\ChannelSurfCli\dotnet'.
   at System.IO.Win32FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.Win32FileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName)
   at ChannelSurfCli.Utils.Files.DecompressSlackArchiveFile(String zipFilePath, String tempPath) in C:\Users\Cassidy's PC\Desktop\ChannelSurf-master\ChannelSurfCli\Utils\Files.cs:line 26
   at ChannelSurfCli.Program.Main(String[] args) in C:\Users\Cassidy's PC\Desktop\ChannelSurf-master\ChannelSurfCli\Program.cs:line 135

C:\Users\Cassidy's PC\Desktop\ChannelSurf-master\ChannelSurfCli>

**Comment by Montana420** [comment]
i did skip the build section because i couldn't seem to find an option to build in the menu.

Build ChannelSurfCli
Open the cloned code from this repository in Visual Studio, Visual Studio Code, or your favorite editor
Update appsettings.json in the ChannelSurfCli folder. Within the section called "AzureAd", update the fields with your tenant name (TenantId), Application ID (ClientId), and Redirect URI (AadRedirectUri). You can leave the value for AadInstance as-is.
NOTE: In previous versions of ChannelSurfCli, these values were stored in Program.cs. If you're upgrading to this new version, please move your settings into appsettings.json as described above.
Or, you can leave these values empty and provide them whenever you run the application.
Build ChannelSurfCli
In Visual Studio select ChannelSurfCli from the Solution Explorer, then from the top menu pick Build -> BuildSurfCli
Or, using the .NET Core SDK, you can perform these steps from the command line
Open a command prompt, and navigate to the ChannelSurfCli folder
dotnet restore
dotnet build

**Comment by dalejohnston82** [comment]
I am as new as you and had the same issue and resolved mine by creating the folder structure inside the ChannelSurfCli folder...
path\to\slack\archive, with the zipped file inside this archive folder.

**Comment by Montana420** [comment]
Hey, thanks i'll give that a try when i get a chance. Thanks!

**Comment by essgit** [comment]
When you are here:
https://github.com/tamhinsf/ChannelSurf#re-create-slack-channels

it says:
- Download the export. It's a ZIP file and will be named in this format: "Your Team export Month Day Year.zip"

- We recommend you re-name the export ZIP file to not have spaces. This will make it easier to work with: i.e. myexport.zip.

**Comment by mengyuw-github** [comment]
Hi Guys, I am stuck at the place right after the authentication. I can successfully sign in in the command prompt. like below

“Let's get started! Sign in to Microsoft with your Teams credentials:
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code *** to authenticate.
You've successfully signed in.  Welcome ***”

Then nothing happens afterwards... 
Any idea why? 

The thing I am suspecting now is the permission to "read/write all groups". To get that permission, it needs grant by the admin of the organization...how do you guys get that...

I appreciate your help.
