### ISSUE TITLE
Unhandled Exception: System.AggregateException:

### ISSUE THREAD

**Issue by gduval** [tamhinsf/ChannelSurf#20]
One or more errors occurred. (AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.

Please advise.

**Comment by eliaspn** [comment]
did you manage to move on?

**Comment by j-mack** [comment]
I'm seeing this same error. Were you ever able to resolve it?

**Comment by talador01** [comment]
I am getting the same as well. Any help would be great!

Unhandled Exception: System.AggregateException: One or more errors occurred. (AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 298982d3-8c55-4eeb-8a10-852217931d00
Correlation ID: ed93319e-c77d-4a41-9a38-83953662a705
Timestamp: 2019-08-01 13:33:35Z) ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.
Trace ID: 298982d3-8c55-4eeb-8a10-852217931d00
Correlation ID: ed93319e-c77d-4a41-9a38-83953662a705
Timestamp: 2019-08-01 13:33:35Z ---> System.Net.Http.HttpRequestException:  Response status code does not indicate success: 401 (Unauthorized). ---> System.Exception: {"error":"invalid_client","error_description":"AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'.\r\nTrace ID: 298982d3-8c55-4eeb-8a10-852217931d00\r\nCorrelation ID: ed93319e-c77d-4a41-9a38-83953662a705\r\nTimestamp: 2019-08-01 13:33:35Z","error_codes":[7000218],"timestamp":"2019-08-01 13:33:35Z","trace_id":"298982d3-8c55-4eeb-8a10-852217931d00","correlation_id":"ed93319e-c77d-4a41-9a38-83953662a705"}
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpClientWrapper.<GetResponseAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient.<GetResponseAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AdalHttpClient.<GetResponseAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendHttpMessageAsync>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenByDeviceCodeHandler.<SendTokenRequestAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenByDeviceCodeAsync>d__24.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ChannelSurfCli.Program.UserLogin()

**Comment by mengyuw-github** [comment]
Got the same error. Try the following. 

In Azure
Click on "ChannelSurfCli", in the page where you get the IDs
click "Supported account types: Multiple organizations"
find "default client type, treat application as a public client": change to yes. 

This worked for me

**Comment by osagendn** [comment]
@mengyuw-github  that worked!!!  Thanks for the info!

**Comment by nati4193** [comment]
> Got the same error. Try the following.
> 
> In Azure
> Click on "ChannelSurfCli", in the page where you get the IDs
> click "Supported account types: Multiple organizations"
> find "default client type, treat application as a public client": change to yes.
> 
> This worked for me

This also works for me too. Thanks.

**Comment by vipulsatyanam** [comment]
> 
> 
> Got the same error. Try the following.
> 
> In Azure
> Click on "ChannelSurfCli", in the page where you get the IDs
> click "Supported account types: Multiple organizations"
> find "default client type, treat application as a public client": change to yes.
> 
> This worked for me



> 
> 
> Got the same error. Try the following.
> 
> In Azure
> Click on "ChannelSurfCli", in the page where you get the IDs
> click "Supported account types: Multiple organizations"
> find "default client type, treat application as a public client": change to yes.
> 
> This worked for me

This works for me as well, thanks buddy
