### ISSUE TITLE
System.NotSupportedException: The given path's format is not supported

### ISSUE THREAD

**Issue by Aysan-kore** [tamhinsf/ChannelSurf#25]
Enter the destination Team number or type "new" to create a new Team: 5
Team ID is 3b8796bd-1b29-4a57-b166-d7c994f64631
Creating temp directory for Slack archive decompression
Temp path is C:\Users\MYUSERNAME\AppData\Local\Temp\tmpD93A.tmp

Unhandled Exception: System.NotSupportedException: The given path's format is not supported.
   at System.IO.Path.GetFullPath(String path)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.Compression.ZipFile.Open(String archiveFileName, ZipArchiveMode mode, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName, Encoding entryNameEncoding)
   at System.IO.Compression.ZipFile.ExtractToDirectory(String sourceArchiveFileName, String destinationDirectoryName)
   at ChannelSurfCli.Utils.Files.DecompressSlackArchiveFile(String zipFilePath, String tempPath) in C:\Temp\ChannelSurfCli\Utils\Files.cs:line 26
   at ChannelSurfCli.Program.Main(String[] args) in C:\Temp\ChannelSurfCli\Program.cs:line 135

**Comment by dweinstein87** [comment]
Hey @Aysan-kore I do not have an answer to your question above, but I am curious how you got around the .net 1.1.2 requirement?

**Comment by pwamburu** [comment]
Hey @Aysan-kore did you figure this out? Stuck here as well. 

@tamhinsf any help would be really appreciated.

**Comment by palec99** [comment]
I am also stuck on the same issue, anyone had a luck with this?

**Comment by averjfis** [comment]
@palec99 I am having the same issue as well.  Any luck on getting this to work?

**Comment by palec99** [comment]
Unfortunately not, I just gave up and turned to commercial tools

Dne čt 5. 10. 2023 21:48 uživatel averjfis ***@***.***>
napsal:

**Comment by averjfis** [comment]
Which tools did you end up going with?  I've been troubleshooting this all day to no avail.

**Comment by palec99** [comment]
I am testing Saketa, it works very well, but it's around 5k USD for my
scenario

Dne čt 5. 10. 2023 22:40 uživatel averjfis ***@***.***>
napsal:
