### ISSUE TITLE
No messages are actually imported

### ISSUE THREAD

**Issue by JanisE** [tamhinsf/ChannelSurf#26]
The migration process seems to be running mostly smoothly. I only get a few messages about already existing items like:
```
Folder creation failure: Microsoft.Graph.ServiceException: Code: nameAlreadyExists
Message: The specified item name already exists.
Channel folder exists
This channel already exists in MS Teams: General
```
Which may be related to the fact that both MS Teams and Slack have the default "General" channel and that I've already done several migration tries now.

I also get a couple of these, which might be related to the same "already existing items" cases, I'm not sure:
```
Inner error

   at Microsoft.Graph.HttpProvider.<SendAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendAsync>d__32`1.MoveNext()
```

Anyway, it does its thing including `Trying to upload file to MS Teams SPo Folder`, `Upload of attachment to MS Teams completed`, `Migrating messages in channel`, asks me whether to create some HTMLs and ends with
```
Scanning messages in Slack channels - done
Tasks complete.  Press any key to exit
```

I see that the channels are created.
In the files tab, I see a folder `channelsurf` which contains folder `messages`, which in turn contains folders `html` and `json`, which then contains `0.html` and `0.json` respectively. (And some bigger channels may contain also `1.html` and `1.json` etc.)
Those `.html` files contain the chat messages.

But the channels themselves do not contain any imported messages. I tried also to log out and back in again. And tried to open Teams in both the web browser and the Teams app, still nothing.

Any ideas?

Could this be related to the users not matcing? As I'm trying this in a test team, where no other users have been added. But it should at least show my own messages, right? How are the users matched?

**Comment by JanisE** [comment]
I just read that those HTML files are what all the migration is about. So, apparently, messages cannot be actually imported as messages.

Sorry for misunderstanding!
